version: '3'
services:
  keycloak:
    # image: registry.ocp4.example.com:8443/keycloak/keycloak:20.0
    image: quay.io/keycloak/keycloak:20.0
    command: start --import-realm --https-key-store-password=redhat --hostname=localhost --hostname-port=8888
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8888:8443"
    volumes:
      - ./quarkus-realm.json:/opt/keycloak/data/import/import.json:z
      - ./server.keystore:/opt/keycloak/conf/server.keystore:z
